-- e-print Oracle initialization script.
-- Run this script on a clean schema. It creates the MinIO and Qiniu template
-- tables, sequences and indexes, and initializes only the template type data.

-- 1. MinIO template type
CREATE TABLE E_PRINT_MINIO_TEMPLATE_TYPE (
    ID NUMBER(18) NOT NULL,
    CODE VARCHAR2(64) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 NOT NULL,
    SORT_NO NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_EPRINT_MINIO_TMPL_TYPE PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_EPRINT_MINIO_TMPL_TYPE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE UNIQUE INDEX UK_EPRINT_MINIO_TMPL_TYPE
    ON E_PRINT_MINIO_TEMPLATE_TYPE (CODE);
CREATE INDEX IDX_EPRINT_MINIO_TT_00
    ON E_PRINT_MINIO_TEMPLATE_TYPE (STATUS, SORT_NO);

COMMENT ON TABLE E_PRINT_MINIO_TEMPLATE_TYPE IS 'MinIO print template type';
COMMENT ON COLUMN E_PRINT_MINIO_TEMPLATE_TYPE.ID IS 'Primary key';
COMMENT ON COLUMN E_PRINT_MINIO_TEMPLATE_TYPE.CODE IS 'Template type code for API';
COMMENT ON COLUMN E_PRINT_MINIO_TEMPLATE_TYPE.NAME IS 'Template type name';
COMMENT ON COLUMN E_PRINT_MINIO_TEMPLATE_TYPE.STATUS IS 'Status: 0 disabled, 1 enabled';
COMMENT ON COLUMN E_PRINT_MINIO_TEMPLATE_TYPE.SORT_NO IS 'Sort number';

-- 2. MinIO template metadata (no initial data)
CREATE TABLE E_PRINT_MINIO_TEMPLATE (
    ID NUMBER(18) NOT NULL,
    TEMPLATE_TYPE_ID NUMBER(18) NOT NULL,
    CODE VARCHAR2(100) NOT NULL,
    BUCKET_NAME VARCHAR2(100) NOT NULL,
    OBJECT_NAME VARCHAR2(500) NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_EPRINT_MINIO_TMPL PRIMARY KEY (ID),
    CONSTRAINT FK_EPRINT_MINIO_TMPL FOREIGN KEY (TEMPLATE_TYPE_ID)
        REFERENCES E_PRINT_MINIO_TEMPLATE_TYPE (ID)
);

CREATE SEQUENCE SEQ_EPRINT_MINIO_TEMPLATE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE UNIQUE INDEX UK_EPRINT_MINIO_TMPL
    ON E_PRINT_MINIO_TEMPLATE (TEMPLATE_TYPE_ID, CODE);
CREATE INDEX IDX_EPRINT_MINIO_TMPL_00
    ON E_PRINT_MINIO_TEMPLATE (TEMPLATE_TYPE_ID, CODE, STATUS);
CREATE INDEX IDX_EPRINT_MINIO_TMPL_01
    ON E_PRINT_MINIO_TEMPLATE (TEMPLATE_TYPE_ID);
CREATE INDEX IDX_EPRINT_MINIO_TMPL_02
    ON E_PRINT_MINIO_TEMPLATE (BUCKET_NAME);
CREATE INDEX IDX_EPRINT_MINIO_TMPL_03
    ON E_PRINT_MINIO_TEMPLATE (OBJECT_NAME);
CREATE INDEX IDX_EPRINT_MINIO_TMPL_04
    ON E_PRINT_MINIO_TEMPLATE (STATUS);

COMMENT ON TABLE E_PRINT_MINIO_TEMPLATE IS 'MinIO print template';
COMMENT ON COLUMN E_PRINT_MINIO_TEMPLATE.ID IS 'Primary key';
COMMENT ON COLUMN E_PRINT_MINIO_TEMPLATE.TEMPLATE_TYPE_ID IS 'Template type ID';
COMMENT ON COLUMN E_PRINT_MINIO_TEMPLATE.CODE IS 'Template code';
COMMENT ON COLUMN E_PRINT_MINIO_TEMPLATE.BUCKET_NAME IS 'MinIO bucket name';
COMMENT ON COLUMN E_PRINT_MINIO_TEMPLATE.OBJECT_NAME IS 'MinIO object name';
COMMENT ON COLUMN E_PRINT_MINIO_TEMPLATE.STATUS IS 'Status: 0 disabled, 1 enabled';

-- 3. Qiniu template type
CREATE TABLE E_PRINT_QINIU_TEMPLATE_TYPE (
    ID NUMBER(18) NOT NULL,
    CODE VARCHAR2(64) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 NOT NULL,
    SORT_NO NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_EPRINT_QINIU_TMPL_TYPE PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_EPRINT_QINIU_TMPL_TYPE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE UNIQUE INDEX UK_EPRINT_QINIU_TMPL_TYPE
    ON E_PRINT_QINIU_TEMPLATE_TYPE (CODE);
CREATE INDEX IDX_EPRINT_QINIU_TT_00
    ON E_PRINT_QINIU_TEMPLATE_TYPE (STATUS, SORT_NO);

COMMENT ON TABLE E_PRINT_QINIU_TEMPLATE_TYPE IS 'Qiniu print template type';
COMMENT ON COLUMN E_PRINT_QINIU_TEMPLATE_TYPE.ID IS 'Primary key';
COMMENT ON COLUMN E_PRINT_QINIU_TEMPLATE_TYPE.CODE IS 'Template type code for API';
COMMENT ON COLUMN E_PRINT_QINIU_TEMPLATE_TYPE.NAME IS 'Template type name';
COMMENT ON COLUMN E_PRINT_QINIU_TEMPLATE_TYPE.STATUS IS 'Status: 0 disabled, 1 enabled';
COMMENT ON COLUMN E_PRINT_QINIU_TEMPLATE_TYPE.SORT_NO IS 'Sort number';

-- 4. Qiniu template metadata (no initial data)
CREATE TABLE E_PRINT_QINIU_TEMPLATE (
    ID NUMBER(18) NOT NULL,
    TEMPLATE_TYPE_ID NUMBER(18) NOT NULL,
    CODE VARCHAR2(100) NOT NULL,
    BUCKET_NAME VARCHAR2(100) NOT NULL,
    OBJECT_NAME VARCHAR2(500) NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_EPRINT_QINIU_TMPL PRIMARY KEY (ID),
    CONSTRAINT FK_EPRINT_QINIU_TMPL FOREIGN KEY (TEMPLATE_TYPE_ID)
        REFERENCES E_PRINT_QINIU_TEMPLATE_TYPE (ID)
);

CREATE SEQUENCE SEQ_EPRINT_QINIU_TEMPLATE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE UNIQUE INDEX UK_EPRINT_QINIU_TMPL
    ON E_PRINT_QINIU_TEMPLATE (TEMPLATE_TYPE_ID, CODE);
CREATE UNIQUE INDEX UK_EPRINT_QINIU_TMPL_OBJ
    ON E_PRINT_QINIU_TEMPLATE (BUCKET_NAME, OBJECT_NAME);
CREATE INDEX IDX_EPRINT_QINIU_TMPL_00
    ON E_PRINT_QINIU_TEMPLATE (TEMPLATE_TYPE_ID, CODE, STATUS);
CREATE INDEX IDX_EPRINT_QINIU_TMPL_01
    ON E_PRINT_QINIU_TEMPLATE (TEMPLATE_TYPE_ID);
CREATE INDEX IDX_EPRINT_QINIU_TMPL_02
    ON E_PRINT_QINIU_TEMPLATE (BUCKET_NAME);
CREATE INDEX IDX_EPRINT_QINIU_TMPL_03
    ON E_PRINT_QINIU_TEMPLATE (OBJECT_NAME);
CREATE INDEX IDX_EPRINT_QINIU_TMPL_04
    ON E_PRINT_QINIU_TEMPLATE (STATUS);

COMMENT ON TABLE E_PRINT_QINIU_TEMPLATE IS 'Qiniu print template';
COMMENT ON COLUMN E_PRINT_QINIU_TEMPLATE.ID IS 'Primary key';
COMMENT ON COLUMN E_PRINT_QINIU_TEMPLATE.TEMPLATE_TYPE_ID IS 'Template type ID';
COMMENT ON COLUMN E_PRINT_QINIU_TEMPLATE.CODE IS 'Template code';
COMMENT ON COLUMN E_PRINT_QINIU_TEMPLATE.BUCKET_NAME IS 'Qiniu bucket name';
COMMENT ON COLUMN E_PRINT_QINIU_TEMPLATE.OBJECT_NAME IS 'Complete Qiniu object key';
COMMENT ON COLUMN E_PRINT_QINIU_TEMPLATE.STATUS IS 'Status: 0 disabled, 1 enabled';

-- 5. Initial template types
INSERT INTO E_PRINT_MINIO_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_MINIO_TMPL_TYPE.NEXTVAL, 'sales_receipt', '销售小票', 1, 10);
INSERT INTO E_PRINT_MINIO_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_MINIO_TMPL_TYPE.NEXTVAL, 'sales_receipt_ed', '销售小票-ed', 1, 20);
INSERT INTO E_PRINT_MINIO_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_MINIO_TMPL_TYPE.NEXTVAL, 'sales_receipt_ed2', '销售小票-ed2', 1, 30);
INSERT INTO E_PRINT_MINIO_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_MINIO_TMPL_TYPE.NEXTVAL, 'sales_receipt_o2o', '销售小票-o2o', 1, 40);
INSERT INTO E_PRINT_MINIO_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_MINIO_TMPL_TYPE.NEXTVAL, 'shipping_label', '物流面单', 1, 50);
INSERT INTO E_PRINT_MINIO_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_MINIO_TMPL_TYPE.NEXTVAL, 'shipping_label_o2o', '物流面单-o2o', 1, 60);
INSERT INTO E_PRINT_MINIO_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_MINIO_TMPL_TYPE.NEXTVAL, 'shipping_label_transfer_out', '物流面单-横调出库', 1, 70);
INSERT INTO E_PRINT_MINIO_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_MINIO_TMPL_TYPE.NEXTVAL, 'shipping_label_return_apply', '物流面单-退货申请', 1, 80);

INSERT INTO E_PRINT_QINIU_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_QINIU_TMPL_TYPE.NEXTVAL, 'sales_receipt', '销售小票', 1, 10);
INSERT INTO E_PRINT_QINIU_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_QINIU_TMPL_TYPE.NEXTVAL, 'sales_receipt_ed', '销售小票-ed', 1, 20);
INSERT INTO E_PRINT_QINIU_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_QINIU_TMPL_TYPE.NEXTVAL, 'sales_receipt_ed2', '销售小票-ed2', 1, 30);
INSERT INTO E_PRINT_QINIU_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_QINIU_TMPL_TYPE.NEXTVAL, 'sales_receipt_o2o', '销售小票-o2o', 1, 40);
INSERT INTO E_PRINT_QINIU_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_QINIU_TMPL_TYPE.NEXTVAL, 'shipping_label', '物流面单', 1, 50);
INSERT INTO E_PRINT_QINIU_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_QINIU_TMPL_TYPE.NEXTVAL, 'shipping_label_o2o', '物流面单-o2o', 1, 60);
INSERT INTO E_PRINT_QINIU_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_QINIU_TMPL_TYPE.NEXTVAL, 'shipping_label_transfer_out', '物流面单-横调出库', 1, 70);
INSERT INTO E_PRINT_QINIU_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_EPRINT_QINIU_TMPL_TYPE.NEXTVAL, 'shipping_label_return_apply', '物流面单-退货申请', 1, 80);

COMMIT;
