-- e-print Oracle initialization script.
-- Run this script on a clean schema after removing existing e-print template tables and sequences.

-- 1. Template type dictionary
CREATE TABLE E_PRINT_TEMPLATE_TYPE (
    ID NUMBER(18) NOT NULL,
    CODE VARCHAR2(64) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 NOT NULL,
    SORT_NO NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_E_PRINT_TEMPLATE_TYPE_00 PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_E_PRINT_TEMPLATE_TYPE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE UNIQUE INDEX UK_E_PRINT_TEMPLATE_TYPE_00
    ON E_PRINT_TEMPLATE_TYPE (CODE);
CREATE INDEX IDX_E_PRINT_TEMPLATE_TYPE_00
    ON E_PRINT_TEMPLATE_TYPE (STATUS, SORT_NO);

COMMENT ON TABLE E_PRINT_TEMPLATE_TYPE IS 'Print template type';
COMMENT ON COLUMN E_PRINT_TEMPLATE_TYPE.ID IS 'Primary key';
COMMENT ON COLUMN E_PRINT_TEMPLATE_TYPE.CODE IS 'Template type code for API';
COMMENT ON COLUMN E_PRINT_TEMPLATE_TYPE.NAME IS 'Template type name';
COMMENT ON COLUMN E_PRINT_TEMPLATE_TYPE.STATUS IS 'Status: 0 disabled, 1 enabled';
COMMENT ON COLUMN E_PRINT_TEMPLATE_TYPE.SORT_NO IS 'Sort number';

-- 2. Template metadata
CREATE TABLE E_PRINT_TEMPLATE (
    ID NUMBER(18) NOT NULL,
    TEMPLATE_TYPE_ID NUMBER(18) NOT NULL,
    CODE VARCHAR2(100) NOT NULL,
    BUCKET_NAME VARCHAR2(100) NOT NULL,
    OBJECT_NAME VARCHAR2(500) NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_E_PRINT_TEMPLATE_00 PRIMARY KEY (ID),
    CONSTRAINT FK_E_PRINT_TEMPLATE_00 FOREIGN KEY (TEMPLATE_TYPE_ID)
        REFERENCES E_PRINT_TEMPLATE_TYPE (ID)
);

CREATE SEQUENCE SEQ_E_PRINT_TEMPLATE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE UNIQUE INDEX UK_E_PRINT_TEMPLATE_00
    ON E_PRINT_TEMPLATE (TEMPLATE_TYPE_ID, CODE);
CREATE INDEX IDX_E_PRINT_TEMPLATE_00
    ON E_PRINT_TEMPLATE (TEMPLATE_TYPE_ID, CODE, STATUS);
CREATE INDEX IDX_E_PRINT_TEMPLATE_01
    ON E_PRINT_TEMPLATE (TEMPLATE_TYPE_ID);
CREATE INDEX IDX_E_PRINT_TEMPLATE_02
    ON E_PRINT_TEMPLATE (BUCKET_NAME);
CREATE INDEX IDX_E_PRINT_TEMPLATE_03
    ON E_PRINT_TEMPLATE (OBJECT_NAME);
CREATE INDEX IDX_E_PRINT_TEMPLATE_04
    ON E_PRINT_TEMPLATE (STATUS);

COMMENT ON TABLE E_PRINT_TEMPLATE IS 'Print template';
COMMENT ON COLUMN E_PRINT_TEMPLATE.ID IS 'Primary key';
COMMENT ON COLUMN E_PRINT_TEMPLATE.TEMPLATE_TYPE_ID IS 'Template type ID';
COMMENT ON COLUMN E_PRINT_TEMPLATE.CODE IS 'Template code';
COMMENT ON COLUMN E_PRINT_TEMPLATE.BUCKET_NAME IS 'MinIO bucket name';
COMMENT ON COLUMN E_PRINT_TEMPLATE.OBJECT_NAME IS 'MinIO object name';
COMMENT ON COLUMN E_PRINT_TEMPLATE.STATUS IS 'Status: 0 disabled, 1 enabled';

-- 3. Initial template types
INSERT INTO E_PRINT_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_E_PRINT_TEMPLATE_TYPE.NEXTVAL, 'sales_receipt', '销售小票', 1, 10);
INSERT INTO E_PRINT_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_E_PRINT_TEMPLATE_TYPE.NEXTVAL, 'sales_receipt_ed', '销售小票-ed', 1, 20);
INSERT INTO E_PRINT_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_E_PRINT_TEMPLATE_TYPE.NEXTVAL, 'sales_receipt_ed2', '销售小票-ed2', 1, 30);
INSERT INTO E_PRINT_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_E_PRINT_TEMPLATE_TYPE.NEXTVAL, 'sales_receipt_o2o', '销售小票-o2o', 1, 40);
INSERT INTO E_PRINT_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_E_PRINT_TEMPLATE_TYPE.NEXTVAL, 'shipping_label', '物流面单', 1, 50);
INSERT INTO E_PRINT_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_E_PRINT_TEMPLATE_TYPE.NEXTVAL, 'shipping_label_o2o', '物流面单-o2o', 1, 60);
INSERT INTO E_PRINT_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_E_PRINT_TEMPLATE_TYPE.NEXTVAL, 'shipping_label_transfer_out', '物流面单-横调出库', 1, 70);
INSERT INTO E_PRINT_TEMPLATE_TYPE (ID, CODE, NAME, STATUS, SORT_NO)
VALUES (SEQ_E_PRINT_TEMPLATE_TYPE.NEXTVAL, 'shipping_label_return_apply', '物流面单-退货申请', 1, 80);

-- 4. Initial default templates
INSERT INTO E_PRINT_TEMPLATE (
    ID,
    TEMPLATE_TYPE_ID,
    CODE,
    BUCKET_NAME,
    OBJECT_NAME,
    STATUS
) VALUES (
    SEQ_E_PRINT_TEMPLATE.NEXTVAL,
    (SELECT ID FROM E_PRINT_TEMPLATE_TYPE WHERE CODE = 'sales_receipt'),
    '01',
    'e-print',
    'templates/print/sales_receipt/01.html',
    1
);

INSERT INTO E_PRINT_TEMPLATE (
    ID,
    TEMPLATE_TYPE_ID,
    CODE,
    BUCKET_NAME,
    OBJECT_NAME,
    STATUS
) VALUES (
    SEQ_E_PRINT_TEMPLATE.NEXTVAL,
    (SELECT ID FROM E_PRINT_TEMPLATE_TYPE WHERE CODE = 'sales_receipt_ed'),
    '01',
    'e-print',
    'templates/print/sales_receipt_ed/01.html',
    1
);

INSERT INTO E_PRINT_TEMPLATE (
    ID,
    TEMPLATE_TYPE_ID,
    CODE,
    BUCKET_NAME,
    OBJECT_NAME,
    STATUS
) VALUES (
    SEQ_E_PRINT_TEMPLATE.NEXTVAL,
    (SELECT ID FROM E_PRINT_TEMPLATE_TYPE WHERE CODE = 'sales_receipt_ed2'),
    '01',
    'e-print',
    'templates/print/sales_receipt_ed2/01.html',
    1
);

INSERT INTO E_PRINT_TEMPLATE (
    ID,
    TEMPLATE_TYPE_ID,
    CODE,
    BUCKET_NAME,
    OBJECT_NAME,
    STATUS
) VALUES (
    SEQ_E_PRINT_TEMPLATE.NEXTVAL,
    (SELECT ID FROM E_PRINT_TEMPLATE_TYPE WHERE CODE = 'sales_receipt_o2o'),
    '01',
    'e-print',
    'templates/print/sales_receipt_o2o/01.html',
    1
);

INSERT INTO E_PRINT_TEMPLATE (
    ID,
    TEMPLATE_TYPE_ID,
    CODE,
    BUCKET_NAME,
    OBJECT_NAME,
    STATUS
) VALUES (
    SEQ_E_PRINT_TEMPLATE.NEXTVAL,
    (SELECT ID FROM E_PRINT_TEMPLATE_TYPE WHERE CODE = 'shipping_label'),
    '01',
    'e-print',
    'templates/print/shipping_label/01.html',
    1
);

INSERT INTO E_PRINT_TEMPLATE (
    ID,
    TEMPLATE_TYPE_ID,
    CODE,
    BUCKET_NAME,
    OBJECT_NAME,
    STATUS
) VALUES (
    SEQ_E_PRINT_TEMPLATE.NEXTVAL,
    (SELECT ID FROM E_PRINT_TEMPLATE_TYPE WHERE CODE = 'shipping_label_o2o'),
    '01',
    'e-print',
    'templates/print/shipping_label_o2o/01.html',
    1
);

INSERT INTO E_PRINT_TEMPLATE (
    ID,
    TEMPLATE_TYPE_ID,
    CODE,
    BUCKET_NAME,
    OBJECT_NAME,
    STATUS
) VALUES (
    SEQ_E_PRINT_TEMPLATE.NEXTVAL,
    (SELECT ID FROM E_PRINT_TEMPLATE_TYPE WHERE CODE = 'shipping_label_transfer_out'),
    '01',
    'e-print',
    'templates/print/shipping_label_transfer_out/01.html',
    1
);

INSERT INTO E_PRINT_TEMPLATE (
    ID,
    TEMPLATE_TYPE_ID,
    CODE,
    BUCKET_NAME,
    OBJECT_NAME,
    STATUS
) VALUES (
    SEQ_E_PRINT_TEMPLATE.NEXTVAL,
    (SELECT ID FROM E_PRINT_TEMPLATE_TYPE WHERE CODE = 'shipping_label_return_apply'),
    '01',
    'e-print',
    'templates/print/shipping_label_return_apply/01.html',
    1
);

COMMIT;
