spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @profiles.active@
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR}
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
      config:
        server-addr: ${NACOS_SERVER_ADDR}
        namespace: e-print-@profiles.active@
        file-extension: yaml
  config:
    import:
      - nacos:@project.artifactId@?group=DEFAULT_GROUP

---
spring:
  config:
    activate:
      on-profile: loc
  cloud:
    nacos:
      config:
        namespace: e-print-loc
      discovery:
        namespace: e-print-loc
---
spring:
  config:
    activate:
      on-profile: uat
  cloud:
    nacos:
      config:
        namespace: e-print-uat
      discovery:
        namespace: e-print-uat
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    nacos:
      config:
        namespace: e-print-prod
      discovery:
        namespace: e-print-prod

---
